/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      screens: {
        'xs': '320px',
        'sm': '640px',
        'md': '768px',
        'tablet': '768px',
        'tablet-lg': '900px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
        // Responsive breakpoints específicos para chat
        'mobile': {'max': '767px'},
        'tablet-only': {'min': '768px', 'max': '1023px'},
        'desktop': {'min': '1024px', 'max': '1439px'},
        'large-screen': {'min': '1440px'},
        // Tablet-specific breakpoints
        'tablet-portrait': {'raw': '(min-width: 768px) and (max-width: 1024px) and (orientation: portrait)'},
        'tablet-landscape': {'raw': '(min-width: 768px) and (max-width: 1024px) and (orientation: landscape)'},
      },
      spacing: {
        '18': '4.5rem',
        '84': '21rem', // Adicionado para tablet
        '88': '22rem',
        '112': '28rem',
        '128': '32rem',
        // Chat-specific spacing
        'chat-xs': '0.5rem',
        'chat-sm': '0.75rem',
        'chat-md': '1rem',
        'chat-lg': '1.25rem',
        'chat-xl': '1.5rem',
        // Responsive spacing
        'mobile-xs': '0.5rem',
        'mobile-sm': '0.75rem',
        'mobile-md': '1rem',
        'tablet-xs': '0.75rem',
        'tablet-sm': '1rem',
        'tablet-md': '1.25rem',
        'desktop-xs': '1rem',
        'desktop-sm': '1.25rem',
        'desktop-md': '1.5rem',
        'large-xs': '1.25rem',
        'large-sm': '1.5rem',
        'large-md': '1.75rem',
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
        // Responsive font sizes
        'mobile-xs': ['0.75rem', { lineHeight: '1rem' }],
        'mobile-sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'mobile-base': ['1rem', { lineHeight: '1.5rem' }],
        'mobile-lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'tablet-xs': ['0.8125rem', { lineHeight: '1.125rem' }],
        'tablet-sm': ['0.9375rem', { lineHeight: '1.375rem' }],
        'tablet-base': ['1.0625rem', { lineHeight: '1.625rem' }],
        'tablet-lg': ['1.1875rem', { lineHeight: '1.875rem' }],
        'desktop-xs': ['0.875rem', { lineHeight: '1.25rem' }],
        'desktop-sm': ['1rem', { lineHeight: '1.5rem' }],
        'desktop-base': ['1.125rem', { lineHeight: '1.75rem' }],
        'desktop-lg': ['1.25rem', { lineHeight: '1.875rem' }],
        'large-xs': ['0.9375rem', { lineHeight: '1.375rem' }],
        'large-sm': ['1.0625rem', { lineHeight: '1.625rem' }],
        'large-base': ['1.1875rem', { lineHeight: '1.875rem' }],
        'large-lg': ['1.375rem', { lineHeight: '2rem' }],
      },
      maxWidth: {
        'xs': '20rem',
        'sm': '24rem',
        'md': '28rem',
        'lg': '32rem',
        'xl': '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
        // Chat-specific max widths
        'chat-mobile': '90%',
        'chat-tablet': '85%',
        'chat-desktop': '80%',
        'chat-large': '75%',
        // Responsive max widths
        'mobile-sm': '22rem',
        'mobile-md': '26rem',
        'mobile-lg': '30rem',
        'tablet-sm': '28rem',
        'tablet-md': '32rem',
        'tablet-lg': '36rem',
        'desktop-sm': '34rem',
        'desktop-md': '38rem',
        'desktop-lg': '42rem',
        'large-sm': '40rem',
        'large-md': '44rem',
        'large-lg': '48rem',
      },
      minHeight: {
        // Chat-specific min heights
        'chat-mobile': 'calc(100vh - 140px)',
        'chat-tablet': 'calc(100vh - 150px)',
        'chat-desktop': 'calc(100vh - 160px)',
        'chat-large': 'calc(100vh - 170px)',
        // Input area min heights
        'input-mobile': '60px',
        'input-tablet': '70px',
        'input-desktop': '80px',
        'input-large': '90px',
        // Dynamic viewport heights for mobile
        'dvh-mobile': 'calc(100dvh - 140px)',
        'dvh-tablet': 'calc(100dvh - 150px)',
      },
      maxHeight: {
        // Chat-specific max heights
        'chat-mobile': 'calc(100vh - 140px)',
        'chat-tablet': 'calc(100vh - 150px)',
        'chat-desktop': 'calc(100vh - 160px)',
        'chat-large': 'calc(100vh - 170px)',
        // Input area max heights
        'input-mobile': '120px',
        'input-tablet': '140px',
        'input-desktop': '160px',
        'input-large': '180px',
        // Dynamic viewport heights for mobile
        'dvh-mobile': 'calc(100dvh - 140px)',
        'dvh-tablet': 'calc(100dvh - 150px)',
      },
      height: {
        // Chat-specific heights
        'chat-mobile': 'calc(100vh - 140px)',
        'chat-tablet': 'calc(100vh - 150px)',
        'chat-desktop': 'calc(100vh - 160px)',
        'chat-large': 'calc(100vh - 170px)',
        // Dynamic viewport heights
        'dvh': '100dvh',
        'dvh-mobile': 'calc(100dvh - 140px)',
        'dvh-tablet': 'calc(100dvh - 150px)',
      },
      animation: {
        'fadeIn': 'fadeIn 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce-slow 3s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
        // Chat-specific animations
        'message-in': 'messageIn 0.3s ease-out',
        'typing': 'typing 1.5s ease-in-out infinite',
        // Responsive animations
        'mobile-fade': 'fadeIn 0.25s ease-out',
        'tablet-fade': 'fadeIn 0.3s ease-out',
        'desktop-fade': 'fadeIn 0.4s ease-out',
      },
      backdropBlur: {
        'xs': '2px',
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        '3xl': '40px',
      },
      blur: {
        'xs': '2px',
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        '3xl': '40px',
      },
      // Chat-specific grid configurations
      gridTemplateColumns: {
        'chat-mobile': 'repeat(2, 1fr)',
        'chat-tablet': 'repeat(3, 1fr)',
        'chat-desktop': 'repeat(6, 1fr)',
        'chat-large': 'repeat(6, 1fr)',
        // Responsive grids
        'mobile-2': 'repeat(2, 1fr)',
        'tablet-3': 'repeat(3, 1fr)',
        'desktop-6': 'repeat(6, 1fr)',
        'large-6': 'repeat(6, 1fr)',
        'auto-fit-mobile': 'repeat(auto-fit, minmax(140px, 1fr))',
        'auto-fit-tablet': 'repeat(auto-fit, minmax(180px, 1fr))',
        'auto-fit-desktop': 'repeat(auto-fit, minmax(220px, 1fr))',
      },
      // Chat-specific gap sizes
      gap: {
        'chat-xs': '0.5rem',
        'chat-sm': '0.75rem',
        'chat-md': '1rem',
        'chat-lg': '1.25rem',
        'chat-xl': '1.5rem',
        // Responsive gaps
        'mobile-xs': '0.5rem',
        'mobile-sm': '0.75rem',
        'mobile-md': '1rem',
        'tablet-xs': '0.75rem',
        'tablet-sm': '1rem',
        'tablet-md': '1.25rem',
        'desktop-xs': '1rem',
        'desktop-sm': '1.25rem',
        'desktop-md': '1.5rem',
        'large-xs': '1.25rem',
        'large-sm': '1.5rem',
        'large-md': '1.75rem',
      },
      // Chat-specific border radius
      borderRadius: {
        'chat-sm': '0.75rem',
        'chat-md': '1rem',
        'chat-lg': '1.25rem',
        'chat-xl': '1.5rem',
        'chat-2xl': '2rem',
      },
      // Chat-specific z-index
      zIndex: {
        'chat-input': '10',
        'chat-overlay': '20',
        'chat-modal': '30',
        'chat-tooltip': '40',
        'chat-dropdown': '50',
      },
    },
  },
  plugins: [],
};